# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='dateVisited',
        ),
        migrations.RemoveField(
            model_name='place',
            name='notes',
        ),
    ]
