# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0002_auto_20170321_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
