# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0003_auto_20170325_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
