# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0004_auto_20170326_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
